/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0Ro1MEAjnpg
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

import { useForm } from "react-hook-form"
import { createOrder } from "../api/task.api"
import { useNavigate } from 'react-router-dom';
import { Checkbox } from "./ui/checkbox"


export function CreateOrder() {


  const navigate = useNavigate();

  const { register, handleSubmit, formState: {
    errors
  } } = useForm();

  const onSubmit = handleSubmit(async (data) => {
    const res = await createOrder(data);
    console.log(res.data.id);
    navigate(`/añadir-productos/${res.data.id}`)
  })

  return (
    <Card>
      <CardHeader>
        <CardTitle>Crear orden</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <form onSubmit={onSubmit}>
          <div className="grid gap-4">
            <div className="grid gap-1">
              <Label className="text-sm" htmlFor="nombre">
                Nombre
              </Label>
              <Input {...register("nombre_cliente")} id="nombre_cliente" placeholder="Entra el nombre para el pedidp" required />
              {errors.nombre && <span>Este campo es requerido</span>}
            </div>


            <div className="flex items-center space-x-2">
              <Checkbox {...register("es_para_llevar")} id="terms" required/>
              <label
                htmlFor="terms"
                className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
              >
                Para Llevar
              </label>
            </div>
            

          </div>
          <Button size="sm">Crear</Button>
        </form>
      </CardContent>
    </Card>
  )
}