/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/beLvekCApww
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "../components/ui/card"
import { Button } from "../components/ui/button"
import { useNavigate } from "react-router-dom"
import { useEffect, useState } from "react"
import { getRestaurants } from "@/api/task.api"
import { Restaurante } from "@/types"

export function MainViewStore() {

  const [restaurante, setRestaurante] = useState<Restaurante>();

  useEffect(() => {  
    async function loadRestaurants() {
      const res = await getRestaurants()
      console.log(res.data);
      setRestaurante(res.data[0]);
    }

    loadRestaurants();


  }, [])

  const navigate = useNavigate();

  const onClick = () => {
    navigate("/editar-restaurante")
  }


  return (
    <Card className="w-full max-w-4xl mx-auto p-5">
      <CardHeader>
        <CardTitle className="text-2xl">🌮 {restaurante?.nombre}</CardTitle>
        <CardDescription>{restaurante?.informacion_contacto}</CardDescription>
        
      </CardHeader>
      <CardContent className="p-0 flex justify-center items-center">
      <Button onClick={onClick} size="sm">Editar tienda</Button>
      </CardContent>
    </Card>
  )
}
