/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/beLvekCApww
 */
import { CardContent, Card } from "./ui/card"
import {  TableBody, Table } from "./ui/table"
import { Product } from "../types"
import { useEffect } from "react";
import { ProductToShowOrder } from "./ProductToShowOrder";



export function MakeOrderProductList({ products }: { products: Array<Product> | undefined }) {
  console.log(products);



  useEffect(() => {

  }, products)



  return (
    <Card className="w-full max-w-4xl mx-auto">
      <CardContent className="p-0">
        <div className="overflow-auto">
          <Table>
            <TableBody>

              {products?.map((product) =>
                <ProductToShowOrder product={product} />
              )}
             
            </TableBody>
          </Table>
        </div>        
      </CardContent>
    </Card>
  )
}
