/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/beLvekCApww
 */
import { CardContent, Card } from "./ui/card"
import { TableCell, TableRow, TableBody, Table } from "./ui/table"
import { Button } from "./ui/button"
import { Product } from "../types"
import { useNavigate } from "react-router-dom";
import { deleteProduct } from "../api/task.api";
import { useState } from "react";



export function ProductList({ products }: { products: Array<Product> | undefined }) {
  console.log(products);

  const [flag, setFlag] = useState(true);

  const navigate = useNavigate();


  const onClick = (id:string) => {
    navigate(`/editar-producto/${id}`);
  }
  const onDelete = async (id:string) => {
    await deleteProduct(id);    
    setFlag(!flag);
  }

  return (
    <Card className="w-full max-w-4xl mx-auto">
      <CardContent className="p-0">
        <div className="overflow-auto">
          <Table>
            <TableBody>

              {products?.map((product) =>
                <TableRow key={product.id}>
                  <TableCell className="border-0">
                    <div className="flex items-center gap-4">
                      <img
                        alt={product.nombre}
                        className="rounded-lg"
                        height="64"
                        src={product.image}
                        style={{
                          aspectRatio: "64/64",
                          objectFit: "cover",
                        }}
                        width="64"
                      />
                      <div className="grid gap-1">
                        <h3 className="font-semibold">{product.nombre}</h3>
                        <p className="text-sm leading-none">
                          {product.descripcion}
                        </p>
                      </div>
                    </div>
                  </TableCell>
                  <TableCell className="border-0">
                    <div className="text-2xl font-semibold">{product.precio}</div>
                  </TableCell>
                  <TableCell className="border-0 flex gap-2">
                  <Button onClick={() => {
                      onClick(product.id);
                    }} size="sm">Editar</Button>
                    <Button onClick={() => {
                      onDelete(product.id)
                    }} size="sm" variant="destructive">Eliminar</Button>
                  </TableCell>
                </TableRow>
              )}
             
            </TableBody>
          </Table>
        </div>        
      </CardContent>
    </Card>
  )
}
